### ISSUE TITLE
Invalid option: wait: -n on MacOS

### ISSUE THREAD

**Issue by m4tt72** [mikehardy/jetifier#14]
Running `npx jetify` exits with error on MacOS:

```
/node_modules/.bin/jetify: line 50: wait: -n: invalid option
wait: usage: wait [n]
```

**Comment by mikehardy** [comment]
Dang - I'm still working on a feature on my main machine - linux - and haven't cross-tested on mac yet

Please downgrade to the release before the performance fix and it should work - that's version 1.2.0

Next version will work on macOS as well, sorry for the hassle

**Comment by mikehardy** [comment]
I'll have this fixed in just a few minutes too likely, so you could also just wait ;-)

**Comment by m4tt72** [comment]
We were facing the same issues with AndroidX migration 2 days ago and I had to create something similar using Node before I stumble upon your solution. 
You can check it out here: https://github.com/Fluicity/jetifire

**Comment by mikehardy** [comment]
version 1.3.2 live on npmjs now
For bash less than 5 (macOS built-in) it does a bursty parallelism now but if it detects bash >= 5 you still get continuous job flow

@m4tt72 that does look interesting! I landed on a script solution because it existed and it seems to be working just fine, so I will likely just sit with it and let it roll now, but if someone wanted to PR a second implementation in javascript I'd welcome it, and after testing it a bit I could switch over to it
