### ISSUE TITLE
[Feature Request] Ability to specify custom folder where to run jetify

### ISSUE THREAD

**Issue by jayshah123** [mikehardy/jetifier#65]
Add Ability to specify custom folder where to run jetify.
Currently the tool fails if try to run on any non node_modules directory.

**Comment by mikehardy** [comment]
Hi there! I will no longer personally work on this project as it's utility is nearly at an end with react-native having transitioned almost 4 versions ago and the rest of the world moving on. I suggest for any remaining modules that haven't migrated to AndroidX you propose PRs to them upstream or use patch-package in order to either patch this module to do what you need, or to patch the offending module. AndroidX should be implemented everywhere at this point.

If you proposed a really clean PR, I could merge it, but I won't spend any time implementing it myself - it's just not a priority vs higher impact things I can work on - hopefully you understand
