### ISSUE TITLE
Vulnerability issue from jdom2-2.0.6.jar (CVE-2021-33813)

### ISSUE THREAD

**Issue by congshengwu** [mikehardy/jetifier#70]
Hi, Author.

Do you have any plan to upgrade jdom from 2.0.6 to 2.0.6.1, which may fix [CVE-2021-33813](https://github.com/advisories/GHSA-2363-cqg2-863c).

Reference: https://github.com/hunterhacker/jdom/releases/tag/JDOM-2.0.6.1

And thank you for your contribution to open source code.

**Comment by mikehardy** [comment]
Hi there! I do not plan to invest any more time in this project personally, no one should be using non-AndroidX libraries at this point, and thus no one should be using this utility any more at this point (that is: you should use the `--no-jetifier` command line option for react-native build so this does not even run, and if you still have dependencies that need it, you should go patch them so jetifier is really not needed)

If this is important to you, I can merge a well-thought-out PR if you propose one though

**Comment by speedoholic** [comment]
> Hi there! I do not plan to invest any more time in this project personally, no one should be using non-AndroidX libraries at this point, and thus no one should be using this utility any more at this point (that is: you should use the `--no-jetifier` command line option for react-native build so this does not even run, and if you still have dependencies that need it, you should go patch them so jetifier is really not needed)
> 
> If this is important to you, I can merge a well-thought-out PR if you propose one though

@mikehardy : Could you please consider adding these comments at the top of your README file? Since the utility gets installed automatically, many developers end up getting the utility installed.

Currently, there are two vulnerabilities associated with jetifier:

1. [CVE-2021-33813](https://github.com/advisories/GHSA-2363-cqg2-863c).
2. [sonatype-2021-1694](https://ossindex.sonatype.org/vulnerability/sonatype-2021-1694?component-type=maven&component-name=com.google.code.gson%2Fgson&utm_source=dependency-check&utm_medium=integration&utm_content=6.1.1).

**Comment by mikehardy** [comment]
The utility no longer gets installed automatically on current versions of anything, or it should not - if it does then whoever still has a dependency on this project needs a PR to remove it so that it is never installed.

I can update the README to say the project has achieved its purpose (it did!) and its time is over (because its time is over, it is obsolete)
