### ISSUE TITLE
react-native-maps seems not to convert

### ISSUE THREAD

**Issue by rborn** [mikehardy/jetifier#8]
Just a heads-up, I got this report, didn't test myself. Sorry if it's not the case 😢
🤗
https://github.com/react-native-community/react-native-maps/issues/2839#issuecomment-503454543

**Comment by rborn** [comment]
more details here: https://github.com/mikehardy/jetifier/issues/9 (not related to rn-maps maybe?)

**Comment by mikehardy** [comment]
I tried but could not reproduce - fork the demonstrator and make it fail, and we can fix it? https://github.com/mikehardy/rn-androidx-demo/commit/a5ee3f894470b310144e8c94bd1ec94862b08b6b

**Comment by jameslporter** [comment]
Cannot find a version of 'androidx.appcompat:appcompat' that satisfies the version constraints: 
   Dependency path 'Docent:react-native-maps:unspecified' --> 'com.android.support:appcompat-v7:28.0.0' because of the following reason: ENABLE_JETIFIER is enabled
   Constraint path 'Docent:react-native-maps:unspecified' --> 'androidx.appcompat:appcompat:{strictly 1.0.0}' because of the following reason: debugRuntimeClasspath uses version 1.0.0
   Dependency path 'Docent:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.60.0' --> 'androidx.appcompat:appcompat:1.0.2'
